[package]
name = "ynab-reimbursements"
version = "0.1.0"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

[dependencies]
cursive = "0.12"
# cursive = { version = "0.12", default-features = false, features = ["crossterm-backend"] }
cursive_table_view = "0.10"
directories = "2.0"
snafu = "0.4"
ynab-api = "1.0"
